import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Prisma-generated artifacts (regenerated by `prisma contract emit`):
    "src/prisma/contract.json",
    "src/prisma/contract.d.ts",
    // Prisma migration snapshots (rendered by `prisma migration plan`):
    "migrations/snapshots/**",
  ]),
]);

export default eslintConfig;
